### ISSUE TITLE
autocomplete only first word

### ISSUE THREAD

**Issue by freestyle68** [codelibs/fess#1194] opened 2017-07-27 11:30 UTC
Why autocomplete suggest only first word?

After inserted the first word, the next words never are suggested.

Should I change mapping of suggest index?

**Comment by marevol** [comment] 2017-07-28 12:43
We could not reproduce it.
Need more info...

**Comment by freestyle68** [comment] 2017-07-28 15:23
browser locale setting: US ENG

Go to http://search.n2sm.co.jp

and search for

"commercial" and then start to digit "sup".

There are 2588 results with the query 

commercial support

but support is never suggested.

Perhaps it happens because of stemming? (the word "commercial" is never suggested as a single word because of stemming).

I also tried with 

support fess  but fess is never suggested. In this case the word "support" is suggested.

**Comment by marevol** [comment] 2017-07-29 00:45
This issue has 2 problem:
- multiple suggest words
- stemming

For multiple suggest words, suggest words are generated from:
- Crawled contents: multiple words are NOT supported.
- Search logs: multiple words are supported.
- [Admin page](http://fess.codelibs.org/11.2/admin/suggest-guide.html): multiple words are supported.

So, if several users search by "commercial support", it will be displayed.

For stemming, it will be fixed in next release...

**Comment by marevol** [comment] 2017-07-29 01:20
> For stemming, it will be fixed in next release...

Fess suggest does not apply stemming.
commerci is in crawled documents. 
Missing "commercial" seems to be from other causes...

**Comment by freestyle68** [comment] 2017-07-30 17:00
> Crawled contents: multiple words are NOT supported.

hope to see this in the future because this is a must have for a search engine (also with "did you mean?").

Thank you very much for your effort.

**Closed** 2017-07-30 17:00 UTC
Labels: question
